// Code generated by goctl. DO NOT EDIT.
// Source: {{SERVICE_NAME}}.proto

package server

import (
	"context"

	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/internal/logic/base"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/internal/svc"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/types/{{SERVICE_NAME}}"
)

type {{SERVICE_NAME_UPPER}}Server struct {
	svcCtx *svc.ServiceContext
	{{SERVICE_NAME}}.Unimplemented{{SERVICE_NAME_UPPER}}Server
}

func New{{SERVICE_NAME_UPPER}}Server(svcCtx *svc.ServiceContext) *{{SERVICE_NAME_UPPER}}Server {
	return &{{SERVICE_NAME_UPPER}}Server{
		svcCtx: svcCtx,
	}
}

func (s *{{SERVICE_NAME_UPPER}}Server) InitDatabase(ctx context.Context, in *{{SERVICE_NAME}}.Empty) (*{{SERVICE_NAME}}.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
