// Code generated by goctl. DO NOT EDIT.
// goctls v1.12.0

package handler

import (
	"net/http"

	base "github.com/coder-lulu/newbee-{{SERVICE_NAME}}-api/internal/handler/base"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)
}
