// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/{{SERVICE_NAME}}"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// {{SERVICE_NAME_UPPER}} is the client for interacting with the {{SERVICE_NAME_UPPER}} builders.
	{{SERVICE_NAME_UPPER}} *{{SERVICE_NAME_UPPER}}Client
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.{{SERVICE_NAME_UPPER}} = New{{SERVICE_NAME_UPPER}}Client(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Io:     New{{SERVICE_NAME_UPPER}}Client(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Io:     New{{SERVICE_NAME_UPPER}}Client(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Io.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.{{SERVICE_NAME_UPPER}}.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.{{SERVICE_NAME_UPPER}}.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *{{SERVICE_NAME_UPPER}}Mutation:
		return c.{{SERVICE_NAME_UPPER}}.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// {{SERVICE_NAME_UPPER}}Client is a client for the {{SERVICE_NAME_UPPER}} schema.
type {{SERVICE_NAME_UPPER}}Client struct {
	config
}

// New{{SERVICE_NAME_UPPER}}Client returns a client for the Io from the given config.
func New{{SERVICE_NAME_UPPER}}Client(c config) *{{SERVICE_NAME_UPPER}}Client {
	return &{{SERVICE_NAME_UPPER}}Client{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `{{SERVICE_NAME}}.Hooks(f(g(h())))`.
func (c *{{SERVICE_NAME_UPPER}}Client) Use(hooks ...Hook) {
	c.hooks.{{SERVICE_NAME_UPPER}} = append(c.hooks.{{SERVICE_NAME_UPPER}}, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `{{SERVICE_NAME}}.Intercept(f(g(h())))`.
func (c *{{SERVICE_NAME_UPPER}}Client) Intercept(interceptors ...Interceptor) {
	c.inters.{{SERVICE_NAME_UPPER}} = append(c.inters.{{SERVICE_NAME_UPPER}}, interceptors...)
}

// Create returns a builder for creating a {{SERVICE_NAME_UPPER}} entity.
func (c *{{SERVICE_NAME_UPPER}}Client) Create() *{{SERVICE_NAME_UPPER}}Create {
	mutation := new{{SERVICE_NAME_UPPER}}Mutation(c.config, OpCreate)
	return &{{SERVICE_NAME_UPPER}}Create{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of {{SERVICE_NAME_UPPER}} entities.
func (c *{{SERVICE_NAME_UPPER}}Client) CreateBulk(builders ...*{{SERVICE_NAME_UPPER}}Create) *{{SERVICE_NAME_UPPER}}CreateBulk {
	return &{{SERVICE_NAME_UPPER}}CreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *{{SERVICE_NAME_UPPER}}Client) MapCreateBulk(slice any, setFunc func(*{{SERVICE_NAME_UPPER}}Create, int)) *{{SERVICE_NAME_UPPER}}CreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &{{SERVICE_NAME_UPPER}}CreateBulk{err: fmt.Errorf("calling to {{SERVICE_NAME_UPPER}}Client.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*{{SERVICE_NAME_UPPER}}Create, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &{{SERVICE_NAME_UPPER}}CreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for {{SERVICE_NAME_UPPER}}.
func (c *{{SERVICE_NAME_UPPER}}Client) Update() *{{SERVICE_NAME_UPPER}}Update {
	mutation := new{{SERVICE_NAME_UPPER}}Mutation(c.config, OpUpdate)
	return &{{SERVICE_NAME_UPPER}}Update{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *{{SERVICE_NAME_UPPER}}Client) UpdateOne(_m *{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}UpdateOne {
	mutation := new{{SERVICE_NAME_UPPER}}Mutation(c.config, OpUpdateOne, with{{SERVICE_NAME_UPPER}}(_m))
	return &{{SERVICE_NAME_UPPER}}UpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *{{SERVICE_NAME_UPPER}}Client) UpdateOneID(id int) *{{SERVICE_NAME_UPPER}}UpdateOne {
	mutation := new{{SERVICE_NAME_UPPER}}Mutation(c.config, OpUpdateOne, with{{SERVICE_NAME_UPPER}}ID(id))
	return &{{SERVICE_NAME_UPPER}}UpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for {{SERVICE_NAME_UPPER}}.
func (c *{{SERVICE_NAME_UPPER}}Client) Delete() *{{SERVICE_NAME_UPPER}}Delete {
	mutation := new{{SERVICE_NAME_UPPER}}Mutation(c.config, OpDelete)
	return &{{SERVICE_NAME_UPPER}}Delete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *{{SERVICE_NAME_UPPER}}Client) DeleteOne(_m *{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}DeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *{{SERVICE_NAME_UPPER}}Client) DeleteOneID(id int) *{{SERVICE_NAME_UPPER}}DeleteOne {
	builder := c.Delete().Where({{SERVICE_NAME}}.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &{{SERVICE_NAME_UPPER}}DeleteOne{builder}
}

// Query returns a query builder for {{SERVICE_NAME_UPPER}}.
func (c *{{SERVICE_NAME_UPPER}}Client) Query() *{{SERVICE_NAME_UPPER}}Query {
	return &{{SERVICE_NAME_UPPER}}Query{
		config: c.config,
		ctx:    &QueryContext{Type: Type{{SERVICE_NAME_UPPER}}},
		inters: c.Interceptors(),
	}
}

// Get returns a {{SERVICE_NAME_UPPER}} entity by its id.
func (c *{{SERVICE_NAME_UPPER}}Client) Get(ctx context.Context, id int) (*{{SERVICE_NAME_UPPER}}, error) {
	return c.Query().Where({{SERVICE_NAME}}.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *{{SERVICE_NAME_UPPER}}Client) GetX(ctx context.Context, id int) *{{SERVICE_NAME_UPPER}} {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *{{SERVICE_NAME_UPPER}}Client) Hooks() []Hook {
	return c.hooks.{{SERVICE_NAME_UPPER}}
}

// Interceptors returns the client interceptors.
func (c *{{SERVICE_NAME_UPPER}}Client) Interceptors() []Interceptor {
	return c.inters.{{SERVICE_NAME_UPPER}}
}

func (c *{{SERVICE_NAME_UPPER}}Client) mutate(ctx context.Context, m *{{SERVICE_NAME_UPPER}}Mutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&{{SERVICE_NAME_UPPER}}Create{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&{{SERVICE_NAME_UPPER}}Update{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&{{SERVICE_NAME_UPPER}}UpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&{{SERVICE_NAME_UPPER}}Delete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown {{SERVICE_NAME_UPPER}} mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		{{SERVICE_NAME_UPPER}} []ent.Hook
	}
	inters struct {
		{{SERVICE_NAME_UPPER}} []ent.Interceptor
	}
)
