// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/{{SERVICE_NAME}}"
)

// Io is the model entity for the {{SERVICE_NAME_UPPER}} schema.
type Io struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*{{SERVICE_NAME_UPPER}}) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case {{SERVICE_NAME}}.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Io fields.
func (_m *{{SERVICE_NAME_UPPER}}) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case {{SERVICE_NAME}}.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Io.
// This includes values selected through modifiers, order, etc.
func (_m *{{SERVICE_NAME_UPPER}}) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Io.
// Note that you need to call Io.Unwrap() before calling this method if this Io
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *{{SERVICE_NAME_UPPER}}) Update() *{{SERVICE_NAME_UPPER}}UpdateOne {
	return New{{SERVICE_NAME_UPPER}}Client(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the {{SERVICE_NAME_UPPER}} entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *{{SERVICE_NAME_UPPER}}) Unwrap() *{{SERVICE_NAME_UPPER}} {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Io is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *{{SERVICE_NAME_UPPER}}) String() string {
	var builder strings.Builder
	builder.WriteString("Io(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Ios is a parsable slice of Io.
type Ios []*{{SERVICE_NAME_UPPER}}
