// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/{{SERVICE_NAME}}"
)

// {{SERVICE_NAME_UPPER}}Create is the builder for creating a {{SERVICE_NAME_UPPER}} entity.
type {{SERVICE_NAME_UPPER}}Create struct {
	config
	mutation *{{SERVICE_NAME_UPPER}}Mutation
	hooks    []Hook
}

// Mutation returns the {{SERVICE_NAME_UPPER}}Mutation object of the builder.
func (_c *{{SERVICE_NAME_UPPER}}Create) Mutation() *{{SERVICE_NAME_UPPER}}Mutation {
	return _c.mutation
}

// Save creates the Io in the database.
func (_c *{{SERVICE_NAME_UPPER}}Create) Save(ctx context.Context) (*{{SERVICE_NAME_UPPER}}, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *{{SERVICE_NAME_UPPER}}Create) SaveX(ctx context.Context) *{{SERVICE_NAME_UPPER}} {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *{{SERVICE_NAME_UPPER}}Create) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *{{SERVICE_NAME_UPPER}}Create) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *{{SERVICE_NAME_UPPER}}Create) check() error {
	return nil
}

func (_c *{{SERVICE_NAME_UPPER}}Create) sqlSave(ctx context.Context) (*{{SERVICE_NAME_UPPER}}, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *{{SERVICE_NAME_UPPER}}Create) createSpec() (*{{SERVICE_NAME_UPPER}}, *sqlgraph.CreateSpec) {
	var (
		_node = &Io{config: _c.config}
		_spec = sqlgraph.NewCreateSpec({{SERVICE_NAME}}.Table, sqlgraph.NewFieldSpec({{SERVICE_NAME}}.FieldID, field.TypeInt))
	)
	return _node, _spec
}

// {{SERVICE_NAME_UPPER}}CreateBulk is the builder for creating many Io entities in bulk.
type {{SERVICE_NAME_UPPER}}CreateBulk struct {
	config
	err      error
	builders []*{{SERVICE_NAME_UPPER}}Create
}

// Save creates the Io entities in the database.
func (_c *{{SERVICE_NAME_UPPER}}CreateBulk) Save(ctx context.Context) ([]*{{SERVICE_NAME_UPPER}}, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*{{SERVICE_NAME_UPPER}}, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*{{SERVICE_NAME_UPPER}}Mutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *{{SERVICE_NAME_UPPER}}CreateBulk) SaveX(ctx context.Context) []*{{SERVICE_NAME_UPPER}} {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *{{SERVICE_NAME_UPPER}}CreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *{{SERVICE_NAME_UPPER}}CreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
