// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/{{SERVICE_NAME}}"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/predicate"
)

// {{SERVICE_NAME_UPPER}}Delete is the builder for deleting a {{SERVICE_NAME_UPPER}} entity.
type {{SERVICE_NAME_UPPER}}Delete struct {
	config
	hooks    []Hook
	mutation *{{SERVICE_NAME_UPPER}}Mutation
}

// Where appends a list predicates to the {{SERVICE_NAME_UPPER}}Delete builder.
func (_d *{{SERVICE_NAME_UPPER}}Delete) Where(ps ...predicate.{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}Delete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *{{SERVICE_NAME_UPPER}}Delete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *{{SERVICE_NAME_UPPER}}Delete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *{{SERVICE_NAME_UPPER}}Delete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec({{SERVICE_NAME}}.Table, sqlgraph.NewFieldSpec({{SERVICE_NAME}}.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// {{SERVICE_NAME_UPPER}}DeleteOne is the builder for deleting a single {{SERVICE_NAME_UPPER}} entity.
type {{SERVICE_NAME_UPPER}}DeleteOne struct {
	_d *{{SERVICE_NAME_UPPER}}Delete
}

// Where appends a list predicates to the {{SERVICE_NAME_UPPER}}Delete builder.
func (_d *{{SERVICE_NAME_UPPER}}DeleteOne) Where(ps ...predicate.{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}DeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *{{SERVICE_NAME_UPPER}}DeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{{{SERVICE_NAME}}.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *{{SERVICE_NAME_UPPER}}DeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
