// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/{{SERVICE_NAME}}"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/predicate"
)

// {{SERVICE_NAME_UPPER}}Query is the builder for querying Io entities.
type {{SERVICE_NAME_UPPER}}Query struct {
	config
	ctx        *QueryContext
	order      []{{SERVICE_NAME}}.OrderOption
	inters     []Interceptor
	predicates []predicate.{{SERVICE_NAME_UPPER}}
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the {{SERVICE_NAME_UPPER}}Query builder.
func (_q *{{SERVICE_NAME_UPPER}}Query) Where(ps ...predicate.{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}Query {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *{{SERVICE_NAME_UPPER}}Query) Limit(limit int) *{{SERVICE_NAME_UPPER}}Query {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *{{SERVICE_NAME_UPPER}}Query) Offset(offset int) *{{SERVICE_NAME_UPPER}}Query {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *{{SERVICE_NAME_UPPER}}Query) Unique(unique bool) *{{SERVICE_NAME_UPPER}}Query {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *{{SERVICE_NAME_UPPER}}Query) Order(o ...{{SERVICE_NAME}}.OrderOption) *{{SERVICE_NAME_UPPER}}Query {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first {{SERVICE_NAME_UPPER}} entity from the query.
// Returns a *NotFoundError when no Io was found.
func (_q *{{SERVICE_NAME_UPPER}}Query) First(ctx context.Context) (*{{SERVICE_NAME_UPPER}}, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{{{SERVICE_NAME}}.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) FirstX(ctx context.Context) *{{SERVICE_NAME_UPPER}} {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Io ID from the query.
// Returns a *NotFoundError when no Io ID was found.
func (_q *{{SERVICE_NAME_UPPER}}Query) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{{{SERVICE_NAME}}.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single {{SERVICE_NAME_UPPER}} entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one {{SERVICE_NAME_UPPER}} entity is found.
// Returns a *NotFoundError when no Io entities are found.
func (_q *{{SERVICE_NAME_UPPER}}Query) Only(ctx context.Context) (*{{SERVICE_NAME_UPPER}}, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{{{SERVICE_NAME}}.Label}
	default:
		return nil, &NotSingularError{{{SERVICE_NAME}}.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) OnlyX(ctx context.Context) *{{SERVICE_NAME_UPPER}} {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Io ID in the query.
// Returns a *NotSingularError when more than one Io ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *{{SERVICE_NAME_UPPER}}Query) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{{{SERVICE_NAME}}.Label}
	default:
		err = &NotSingularError{{{SERVICE_NAME}}.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Ios.
func (_q *{{SERVICE_NAME_UPPER}}Query) All(ctx context.Context) ([]*{{SERVICE_NAME_UPPER}}, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*{{SERVICE_NAME_UPPER}}, *{{SERVICE_NAME_UPPER}}Query]()
	return withInterceptors[[]*{{SERVICE_NAME_UPPER}}](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) AllX(ctx context.Context) []*{{SERVICE_NAME_UPPER}} {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Io IDs.
func (_q *{{SERVICE_NAME_UPPER}}Query) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select({{SERVICE_NAME}}.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *{{SERVICE_NAME_UPPER}}Query) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*{{SERVICE_NAME_UPPER}}Query](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *{{SERVICE_NAME_UPPER}}Query) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *{{SERVICE_NAME_UPPER}}Query) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the {{SERVICE_NAME_UPPER}}Query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *{{SERVICE_NAME_UPPER}}Query) Clone() *{{SERVICE_NAME_UPPER}}Query {
	if _q == nil {
		return nil
	}
	return &{{SERVICE_NAME_UPPER}}Query{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]{{SERVICE_NAME}}.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.{{SERVICE_NAME_UPPER}}{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (_q *{{SERVICE_NAME_UPPER}}Query) GroupBy(field string, fields ...string) *{{SERVICE_NAME_UPPER}}GroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &{{SERVICE_NAME_UPPER}}GroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = {{SERVICE_NAME}}.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (_q *{{SERVICE_NAME_UPPER}}Query) Select(fields ...string) *{{SERVICE_NAME_UPPER}}Select {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &{{SERVICE_NAME_UPPER}}Select{{{SERVICE_NAME_UPPER}}Query: _q}
	sbuild.label = {{SERVICE_NAME}}.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a {{SERVICE_NAME_UPPER}}Select configured with the given aggregations.
func (_q *{{SERVICE_NAME_UPPER}}Query) Aggregate(fns ...AggregateFunc) *{{SERVICE_NAME_UPPER}}Select {
	return _q.Select().Aggregate(fns...)
}

func (_q *{{SERVICE_NAME_UPPER}}Query) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !{{SERVICE_NAME}}.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *{{SERVICE_NAME_UPPER}}Query) sqlAll(ctx context.Context, hooks ...queryHook) ([]*{{SERVICE_NAME_UPPER}}, error) {
	var (
		nodes = []*{{SERVICE_NAME_UPPER}}{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*{{SERVICE_NAME_UPPER}}).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Io{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *{{SERVICE_NAME_UPPER}}Query) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *{{SERVICE_NAME_UPPER}}Query) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec({{SERVICE_NAME}}.Table, {{SERVICE_NAME}}.Columns, sqlgraph.NewFieldSpec({{SERVICE_NAME}}.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, {{SERVICE_NAME}}.FieldID)
		for i := range fields {
			if fields[i] != {{SERVICE_NAME}}.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *{{SERVICE_NAME_UPPER}}Query) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table({{SERVICE_NAME}}.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = {{SERVICE_NAME}}.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// {{SERVICE_NAME_UPPER}}GroupBy is the group-by builder for {{SERVICE_NAME_UPPER}} entities.
type {{SERVICE_NAME_UPPER}}GroupBy struct {
	selector
	build *{{SERVICE_NAME_UPPER}}Query
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *{{SERVICE_NAME_UPPER}}GroupBy) Aggregate(fns ...AggregateFunc) *{{SERVICE_NAME_UPPER}}GroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *{{SERVICE_NAME_UPPER}}GroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*{{SERVICE_NAME_UPPER}}Query, *{{SERVICE_NAME_UPPER}}GroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *{{SERVICE_NAME_UPPER}}GroupBy) sqlScan(ctx context.Context, root *{{SERVICE_NAME_UPPER}}Query, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// {{SERVICE_NAME_UPPER}}Select is the builder for selecting fields of {{SERVICE_NAME_UPPER}} entities.
type {{SERVICE_NAME_UPPER}}Select struct {
	*{{SERVICE_NAME_UPPER}}Query
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *{{SERVICE_NAME_UPPER}}Select) Aggregate(fns ...AggregateFunc) *{{SERVICE_NAME_UPPER}}Select {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *{{SERVICE_NAME_UPPER}}Select) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*{{SERVICE_NAME_UPPER}}Query, *{{SERVICE_NAME_UPPER}}Select](ctx, _s.{{SERVICE_NAME_UPPER}}Query, _s, _s.inters, v)
}

func (_s *{{SERVICE_NAME_UPPER}}Select) sqlScan(ctx context.Context, root *{{SERVICE_NAME_UPPER}}Query, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
