// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/{{SERVICE_NAME}}"
	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/ent/predicate"
)

// {{SERVICE_NAME_UPPER}}Update is the builder for updating Io entities.
type {{SERVICE_NAME_UPPER}}Update struct {
	config
	hooks    []Hook
	mutation *{{SERVICE_NAME_UPPER}}Mutation
}

// Where appends a list predicates to the {{SERVICE_NAME_UPPER}}Update builder.
func (_u *{{SERVICE_NAME_UPPER}}Update) Where(ps ...predicate.{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}Update {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the {{SERVICE_NAME_UPPER}}Mutation object of the builder.
func (_u *{{SERVICE_NAME_UPPER}}Update) Mutation() *{{SERVICE_NAME_UPPER}}Mutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *{{SERVICE_NAME_UPPER}}Update) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *{{SERVICE_NAME_UPPER}}Update) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *{{SERVICE_NAME_UPPER}}Update) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *{{SERVICE_NAME_UPPER}}Update) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *{{SERVICE_NAME_UPPER}}Update) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec({{SERVICE_NAME}}.Table, {{SERVICE_NAME}}.Columns, sqlgraph.NewFieldSpec({{SERVICE_NAME}}.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{{{SERVICE_NAME}}.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// {{SERVICE_NAME_UPPER}}UpdateOne is the builder for updating a single {{SERVICE_NAME_UPPER}} entity.
type {{SERVICE_NAME_UPPER}}UpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *{{SERVICE_NAME_UPPER}}Mutation
}

// Mutation returns the {{SERVICE_NAME_UPPER}}Mutation object of the builder.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) Mutation() *{{SERVICE_NAME_UPPER}}Mutation {
	return _u.mutation
}

// Where appends a list predicates to the {{SERVICE_NAME_UPPER}}Update builder.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) Where(ps ...predicate.{{SERVICE_NAME_UPPER}}) *{{SERVICE_NAME_UPPER}}UpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) Select(field string, fields ...string) *{{SERVICE_NAME_UPPER}}UpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated {{SERVICE_NAME_UPPER}} entity.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) Save(ctx context.Context) (*{{SERVICE_NAME_UPPER}}, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) SaveX(ctx context.Context) *{{SERVICE_NAME_UPPER}} {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *{{SERVICE_NAME_UPPER}}UpdateOne) sqlSave(ctx context.Context) (_node *{{SERVICE_NAME_UPPER}}, err error) {
	_spec := sqlgraph.NewUpdateSpec({{SERVICE_NAME}}.Table, {{SERVICE_NAME}}.Columns, sqlgraph.NewFieldSpec({{SERVICE_NAME}}.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Io.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, {{SERVICE_NAME}}.FieldID)
		for _, f := range fields {
			if !{{SERVICE_NAME}}.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != {{SERVICE_NAME}}.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Io{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{{{SERVICE_NAME}}.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
