// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IosColumns holds the columns for the "ios" table.
	IosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// IosTable holds the schema information for the "ios" table.
	IosTable = &schema.Table{
		Name:       "ios",
		Columns:    IosColumns,
		PrimaryKey: []*schema.Column{IosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IosTable,
	}
)

func init() {
}
