// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: {{SERVICE_NAME}}.proto

package io

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Io_InitDatabase_FullMethodName = "/{{SERVICE_NAME}}.{{SERVICE_NAME_UPPER}}/initDatabase"
)

// {{SERVICE_NAME_UPPER}}Client is the client API for Io service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type {{SERVICE_NAME_UPPER}}Client interface {
	// group: base
	InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
}

type ioClient struct {
	cc grpc.ClientConnInterface
}

func New{{SERVICE_NAME_UPPER}}Client(cc grpc.ClientConnInterface) {{SERVICE_NAME_UPPER}}Client {
	return &ioClient{cc}
}

func (c *ioClient) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Io_InitDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// {{SERVICE_NAME_UPPER}}Server is the server API for Io service.
// All implementations must embed UnimplementedIoServer
// for forward compatibility.
type {{SERVICE_NAME_UPPER}}Server interface {
	// group: base
	InitDatabase(context.Context, *Empty) (*BaseResp, error)
	mustEmbedUnimplementedIoServer()
}

// UnimplementedIoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIoServer struct{}

func (UnimplementedIoServer) InitDatabase(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedIoServer) mustEmbedUnimplementedIoServer() {}
func (UnimplementedIoServer) testEmbeddedByValue()            {}

// UnsafeIoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to {{SERVICE_NAME_UPPER}}Server will
// result in compilation errors.
type UnsafeIoServer interface {
	mustEmbedUnimplementedIoServer()
}

func RegisterIoServer(s grpc.ServiceRegistrar, srv {{SERVICE_NAME_UPPER}}Server) {
	// If the following call pancis, it indicates UnimplementedIoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Io_ServiceDesc, srv)
}

func _Io_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.({{SERVICE_NAME_UPPER}}Server).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Io_InitDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.({{SERVICE_NAME_UPPER}}Server).InitDatabase(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Io_ServiceDesc is the grpc.ServiceDesc for Io service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Io_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "{{SERVICE_NAME}}.{{SERVICE_NAME_UPPER}}",
	HandlerType: (*{{SERVICE_NAME_UPPER}}Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDatabase",
			Handler:    _Io_InitDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "{{SERVICE_NAME}}.proto",
}
