// Code generated by goctl. DO NOT EDIT.
// Source: {{SERVICE_NAME}}.proto

package {{SERVICE_NAME}}client

import (
	"context"

	"github.com/coder-lulu/newbee-{{SERVICE_NAME}}-rpc/types/{{SERVICE_NAME}}"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDInt32Resp  = {{SERVICE_NAME}}.BaseIDInt32Resp
	BaseIDInt64Resp  = {{SERVICE_NAME}}.BaseIDInt64Resp
	BaseIDResp       = {{SERVICE_NAME}}.BaseIDResp
	BaseIDStringResp = {{SERVICE_NAME}}.BaseIDStringResp
	BaseIDUint32Resp = {{SERVICE_NAME}}.BaseIDUint32Resp
	BaseResp         = {{SERVICE_NAME}}.BaseResp
	BaseUUIDResp     = {{SERVICE_NAME}}.BaseUUIDResp
	Empty            = {{SERVICE_NAME}}.Empty
	IDInt32Req       = {{SERVICE_NAME}}.IDInt32Req
	IDInt64Req       = {{SERVICE_NAME}}.IDInt64Req
	IDReq            = {{SERVICE_NAME}}.IDReq
	IDStringReq      = {{SERVICE_NAME}}.IDStringReq
	IDUint32Req      = {{SERVICE_NAME}}.IDUint32Req
	IDsInt32Req      = {{SERVICE_NAME}}.IDsInt32Req
	IDsInt64Req      = {{SERVICE_NAME}}.IDsInt64Req
	IDsReq           = {{SERVICE_NAME}}.IDsReq
	IDsStringReq     = {{SERVICE_NAME}}.IDsStringReq
	IDsUint32Req     = {{SERVICE_NAME}}.IDsUint32Req
	PageInfoReq      = {{SERVICE_NAME}}.PageInfoReq
	UUIDReq          = {{SERVICE_NAME}}.UUIDReq
	UUIDsReq         = {{SERVICE_NAME}}.UUIDsReq

	{{SERVICE_NAME_UPPER}} interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	default{{SERVICE_NAME_UPPER}} struct {
		cli zrpc.Client
	}
)

func New{{SERVICE_NAME_UPPER}}(cli zrpc.Client) {{SERVICE_NAME_UPPER}} {
	return &default{{SERVICE_NAME_UPPER}}{
		cli: cli,
	}
}

func (m *default{{SERVICE_NAME_UPPER}}) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := {{SERVICE_NAME}}.New{{SERVICE_NAME_UPPER}}Client(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
